version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: employee-insights-api
    ports:
      - "8082:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    restart: unless-stopped
