spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  r2dbc:
    url: r2dbc:postgresql://192.168.1.20:5432/postgres
    username: postgres
    password: amar1404


---

spring:
  config:
    activate:
      on-profile: prod
  r2dbc:
    url: r2dbc:postgresql://prod-server:5432/amarj
    username: postgres
    password: admin

---
server:
  port: 8083
  error:
    include-message: always

---
spring:
  r2dbc:
    show-sql: true

logging:
  level:
    org.springframework.data.r2dbc: DEBUG
    io.r2dbc.postgresql: TRACE

---

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: emp-insights-db
      username: amar
      password: amar1404
      authentication-database: admin
